language: go
go:
  - 1.7.x
  - tip
gobuild_args: -ldflags "-X main.version=$(git name-rev --tags --name-only $(git rev-parse HEAD))"
before_script:
  - gometalinter --deadline=60s --exclude=_test ./...
deploy:
  provider: releases
  api_key:
    secure: yvCvA95Lwx3Dvb6czlzKoSDAi8F8D8oZnpWogM7Z/2i85KLaXXZrdeyvqcQKoqaHucUfKmBueu+Id2UdobDbl7eXC8aJmGbuzsc1QWPwii2yj+BkcChsrSUQf6o1dh2cQ+jgE23YzESKnth5nVnsx98b+OwiCc2euqEeZQmxFLfWEBs9uhyFCALD7S55+FEmNdWn/4uYH8iXeGz+JnEzhuSz15SiDK2+DthyaSDAt1QKLwrUjqDpdP0JgmwoE0Odb9GkxeO8cDLwFJk8srnSbQ1ym1KYRGUBeTpBV2DZS82IPiHb107KMLalvxcGF9lK17LYHHiniZq27l+SviAG8VgdtYSLkUrmQ3KVgozPRaDbSGHsGB2CR7JfxvfXQkWPzeu9TGi5kXoc88zJofl1GA+Wd3DwvinqW+F5VoMMpzE7CrPLP/Wpp1aupyrzBeQThbZMLWatZM0Vs4PBk0AE4wXI4InG7Ufh+H7nYm4hByctT396TSYX/l6y1TSDG7n+NKw4VHKYUpgEksIFkyqvnmrDOWoByXcYyGmnMncSctjG2NoiKUvcS+g+aWYbxlR68xUebqQyR2/jvkoxgoVjK9eH8XXtWzQxKfLZgf5Lp6+h60PTOL6q8W15DsqlSGr2CecUR78AKmu0XSVfdr4XtN1BNSUn3EgCgzGWMCb0neQ=
  file: jesi
  on:
    repo: ichiban/jesi
